### ISSUE TITLE
Double return in the code

### ISSUE THREAD

**Issue by programer786** [lambdadog/passfail2#2]
Hello,
I was wondering why the code is like this:
`
    if cnt == 2 or cnt == 3:
        return l + ((2, _("Pass"), _("Shortcut keys: 2, 3, 4")),)
    else:
        return l + ((3, _("Pass"), _("Shortcut keys: 2, 3, 4")),)
`

Is there any need for this "if" and "else" since they return the same?

**Comment by lambdadog** [comment]
Strictly speaking they don't return the same, but you're right that this section could be improved -- I admittedly wrote the addon fairly quickly and thoughtlessly, paraphrasing the original Pass/Fail addon with a newer version of the API.

You could probably move the if-else up to assigning a variable that just sets the changed 2/3 in the values returned.

**Comment by lambdadog** [comment]
I'm currently in a fairly busy transitory period in my life so I won't be able to tackle this immediately, but I'll add this to my tasks to get to once I have more time for my open source work.

**Comment by lambdadog** [comment]
I suspect there are a number of places I'd like to refactor the code if I got the chance to look at it again -- I could probably derive both this value and the `remap` map from the a singular mapping from number-of-answers to location-of-"good"-button, that just looked something like

```py
goodButton = {
  2: 2,
  3: 2,
  4: 3
}
```
