### ISSUE TITLE
Publish on Ankiweb

### ISSUE THREAD

**Issue by AriaMoradi** [lambdadog/passfail2#3]
Any plan to publish this on ankiweb?

For now I uploaded it here: https://ankiweb.net/shared/info/1943155256

**Comment by lambdadog** [comment]
Thanks for bringing it to my attention, I'd just been installing it from my own Releases page, but for sharing AnkiWeb is definitely better.

I've uploaded it here: https://ankiweb.net/shared/info/876946123

I'll add it to the `README.md`, ideally you could go ahead and remove yours so it's possible to centralize on official release.

**Comment by AriaMoradi** [comment]
I removed my upload

**Comment by lambdadog** [comment]
Appreciated!
