### ISSUE TITLE
How can I translate "FAIL" "PASS" to my language?

### ISSUE THREAD

**Issue by Alexnoj** [lambdadog/passfail2#4]
Thanks

**Comment by GriefBacon** [comment]
I had a similar question.

I followed the suggestion you provided, lambdadog, and I was wondering if you could confirm that I did it correctly.
Here is a pastebin link: https://pastebin.com/gaxQv5AE

I just wanted to change pass/fail to the Japanese equivalent.

**Comment by lambdadog** [comment]
@GriefBacon this should work, yes

Apologies for still not having i18n set up after all this time -- it really shouldn't be that hard to set up something simple for it but I simply never got around to it.

**Comment by lambdadog** [comment]
As of the latest release this is customizable in Pass/Fail 2's config, which is reachable via the Addons menu.
