### ISSUE TITLE
How to make it work on iPhone Anki?

### ISSUE THREAD

**Issue by tonidayo** [lambdadog/passfail2#6]
Hello, how can I make this work and function on iPhone Anki app ?

**Comment by lambdadog** [comment]
Unfortunately neither the iPhone or Android apps support addons, or at least the type of addon Pass/Fail 2 is (I believe the Android version does have an API, but Pass/Fail 2's functionality wouldn't be supported by it).

You could maybe play around with the configuration to see if there's something close you can achieve -- personally on AnkiDroid I have my settings to fullscreen when reviewing (which hides the buttons) and set my gesture settings so only "Again" and "Good" (corresponding to Fail, and Pass) actually have gestures assigned.
