### ISSUE TITLE
Pass Button Links to "Hard" 2.1.54

### ISSUE THREAD

**Issue by daver12345** [lambdadog/passfail2#7]
Hi there, just wanted to let you know that in the new update of Anki, the Pass button links to "Hard" now instead of "Good". Here are a few images to show what I mean.

![](https://i.imgur.com/EvRG15J.png)
![](https://i.imgur.com/Tpk13ef.png)

**Comment by daver12345** [comment]
I am using the Apple Silicon version of Anki atm, so not sure if this is a Silicon specific issue, but I would assume not.

**Comment by daver12345** [comment]
<img width="408" alt="image" src="https://user-images.githubusercontent.com/31458212/178917779-a4c3c182-c700-4ae1-a4ef-d218a7ee694e.png">
I temporarily fixed this by switching the 2, "Pass" to a 3 but not sure if this is a permanent solution.

**Comment by daver12345** [comment]
This did not in fact fix the actual action, just the preview of the button timing.

**Comment by daver12345** [comment]
<img width="429" alt="image" src="https://user-images.githubusercontent.com/31458212/178918728-ba737960-f284-4966-b55b-724334432b10.png">
Also changed this, now it works.

**Comment by lambdadog** [comment]
Thank you! Sorry about that, just caught this myself.

I just released an update to fix it, please try it and let me know if you have any more issues!

**Comment by lambdadog** [comment]
This was an attempt to make "Pass" show "Shortcut key: 2" on hover without having to reimplement [`Reviewer._answerButton`](https://github.com/ankitects/anki/blob/f6390e9455365f696b0bd06f9be398e6698baf38/qt/aqt/reviewer.py#L844-L874) wholesale, but unfortunately it caused some issues I wasn't able to catch before release, so with my fix the on-hover popup text is reverted to 3, but 2, 3, and 4 all still serve as shortcut keys for Pass.

**Comment by daver12345** [comment]
I see, that makes sense. I updated and as you said 2, 3, and 4 work as shortcut keys. Thanks for fixing!
