### ISSUE TITLE
Shorcuts doub

### ISSUE THREAD

**Issue by ralts00** [lambdadog/passfail2#9]
Thanks for the Add-on
What key should I press for the "Pass" shortcut?
What happens if I squeeze space bar?

**Comment by lambdadog** [comment]
If you squeeze the spacebar, Anki will submit the currently selected answer (the Enter key does the same). The selected answer is, by default, "Pass", but there should be a visual indicator that will show the currently selected answer depending on your Anki theme.

The shortcut key for "Pass" itself is the 2 button.
